### ISSUE TITLE
Incorrect week iteration in _burn_boost() method

### ISSUE THREAD

**Issue by Kogaroshi** [curvefi/curve-veBoost#14]
### Issue:

In the `_burn_boost` method, when the Boost being burned is the current `next_expiry`, and there is not more Boosts on that same `expire_time`, the method will loop over the next 10 years, by a weekly increment, to find the next Boost to expire, and set its `expire_time` as the new next_expiry.
But because the range on line [320](https://github.com/curvefi/curve-veBoost/blob/4dacb54480b6a8abdca8167ec3a62e4ec0ce03d8/contracts/VotingEscrowDelegation.vy#L320) is starting at 1, and on line [325](https://github.com/curvefi/curve-veBoost/blob/4dacb54480b6a8abdca8167ec3a62e4ec0ce03d8/contracts/VotingEscrowDelegation.vy#L325), `week_ts` is calculated using `expire_time + WEEK * (i + 1)`, the first `week_ts` to be checked is not  `expire_time + WEEK`, but `expire_time + WEEK * 2`.
If the next Boost (and the only other Boost from the delegator), is expiring on `expire_time + WEEK`, it will never be found, and the method will fail and raise `Failed to find next expiry`

### Failing scenario:
- Alice issues Boost to Bob, expiring on week N
- Alice issues a 2n Boost, to Charlie, expiring on week N+1
- When trying to cancel the Boost 1, the loop will never check week N+1 to find the `next_expiry`, and fail

**Comment by skellet0r** [comment]
fixed via #15
